### PR TITLE
Add DomainConfig and ResourceConfig to ease configuration

### PR DESCRIPTION
**Pull request by dkellner**
_(From the commit message of the first commit:)_
This is a major rewrite of the `DOMAIN` config generation. It obsoletes the `registerSchema` decorator in favor of `DomainConfig` and `ResourceConfig` which are used to render Eve domain and resource configuration dictionaries.

Advantages over `registerSchema` include:
- free from side-effects, i.e. not altering domain models
- automatic and reasonable configuration of `id_field`, `item_lookup_field` and `item_url`
- robust way of specifying target resources for relationships when there is more than one resource per model

-----

This addresses a number of issues and other PRs: #46, #52, #68, #95, #96, #97, #139, #144

-----

Unfortunately this is another **breaking change** scheduled for 0.5.0. I've intially planned rewriting `registerSchema` to use the new configuration mechanism, but it proved to be not easy enough to be worth it. I've included an "Upgrading" section in the docs (see `upgrading.rst`).

@joystein, @bomb-on, @ralphsmith80 can you test this with real-world applications to see if we miss something important? I will do the same. Just wanted to create this PR finally as I know some people are waiting for a release. But I want to have the (already known) breaking changes together in one release and I've planned doing this here for some time now.

### CODE REVIEW

**Comment by joystein** [comment]
@dkellner , this is excellent news! Right now I'm unsure when i get to test these changes, but i will try to find time within the next couple of weeks.

**Comment by bomb-on** [comment]
Amazing work!
Sorry for my delay, I was on vacation until yesterday... I will try to test it out a bit this week (also with my real-world app) and report back here ASAP!

**Comment by bomb-on** [comment]
My "observations"  as follows... :)

**Installation**
- Using OS X 10.12.6 with Python 3.4.5 as default interpreter
- started with completely fresh Python environment
- `pip` installed https://github.com/pyeve/eve-sqlalchemy/pull/152/commits/1c1088d84e5a865970ac4850a923c2cc587d5df1
- got installed dependencies: Eve-0.6.4, Flask-SQLAlchemy-2.2, SQLAlchemy-1.1.12

**Code**
- removed `registerSchema()` decorators
- configured my `DOMAIN` with `DomainConfig()` and `ResourceConfig()` classes (e.g. `DOMAIN = DomainConfig({'users': ResourceConfig(Users), 'data': ResourceConfig(Data)}).render()`)
- left my models intact (just 2 simple tables with one-to-many relationship)
- still had to "manually" configure `resource_methods` and `projection` for my endpoints (I assume this will be defined in `ResourceConfig()` in the future?)

**Results**
In my app I defined only 2 endpoints: `users` and `data`. Tables are very simple:

```python
class Users(CommonColumns):
    __tablename__ = 'users'
    __table_args__ = {'schema': 'testing'}

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    user_name = Column(Text, nullable=False, unique=True)
    key = Column(Text, nullable=False, unique=True)
    secret = Column(Text, nullable=False, unique=True)


class Data(CommonColumns):
    __tablename__ = 'data'
    __table_args__ = {'schema': 'testing'}

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    user_id = Column(ForeignKey('testing.users.id', ondelete='RESTRICT',
                                onupdate='CASCADE'), nullable=False)
    user_data = Column(JSON, nullable=False)
    request_session = Column(Text)

    user = relationship('Users')
```

I can successfully `POST` and `GET` the `/data` endpoint.

However, if I try to `GET /users` (the table has 2 rows only, just to be able to differentiate them by `id`), I get the `AttributeError: type object 'Users' has no attribute 'user_id'` no matter which `id` I try to retrieve.

Full stack traceback:
```
Traceback (most recent call last):
  File "/Users/oxxo/.pyenv/versions/klappir/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/oxxo/.pyenv/versions/klappir/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/oxxo/.pyenv/versions/klappir/lib/python3.4/site-packages/eve/endpoints.py", line 92, in item_endpoint
    response = getitem(resource, **lookup)
  File "/Users/oxxo/.pyenv/versions/klappir/lib/python3.4/site-packages/eve/methods/common.py", line 242, in rate_limited
    return f(*args, **kwargs)
  File "/Users/oxxo/.pyenv/versions/klappir/lib/python3.4/site-packages/eve/auth.py", line 79, in decorated
    return f(*args, **kwargs)
  File "/Users/oxxo/.pyenv/versions/klappir/lib/python3.4/site-packages/eve/methods/common.py", line 949, in decorated
    r = f(resource, **combined_args)
  File "/Users/oxxo/.pyenv/versions/klappir/lib/python3.4/site-packages/eve/methods/get.py", line 212, in getitem
    document = app.data.find_one(resource, req, **lookup)
  File "/Users/oxxo/.pyenv/versions/3.4.5/envs/klappir/src/eve-sqlalchemy/eve_sqlalchemy/__init__.py", line 138, in find_one
    client_embedded)
  File "/Users/oxxo/.pyenv/versions/3.4.5/envs/klappir/src/eve-sqlalchemy/eve_sqlalchemy/__init__.py", line 332, in _datasource_ex
    filter_ = self._parse_filter(model, filter_)
  File "/Users/oxxo/.pyenv/versions/3.4.5/envs/klappir/src/eve-sqlalchemy/eve_sqlalchemy/__init__.py", line 301, in _parse_filter
    filter = parse_dictionary(filter, model)
  File "/Users/oxxo/.pyenv/versions/3.4.5/envs/klappir/src/eve-sqlalchemy/eve_sqlalchemy/parser.py", line 63, in parse_dictionary
    attr = getattr(model, k)
AttributeError: type object 'Users' has no attribute 'user_id'
```

To be honest, I didn't try to dig deeper into problem, there's plenty of work waiting for me after the long summer vacation ^^
I hope this will be helpful anyway, let me know if I can provide some more info about my setup. As soon as I clean up my backlog a bit, I'll try to put some more time into v0.5 milestone too ;)

Also, all tests passed on my side!! :)

**Comment by dkellner** [comment]
@bomb-on Are you using Authentication with this `User` model? Your stacktrace shows that `find_one` was called, which normally not happens for GETting a resource (like `GET /users`). And/or do you use [predefined database filters](http://python-eve.org/config.html#predefined-database-filters)?

I've added working examples for one-to-many, many-to-one and many-to-many relationships. Maybe this will help to spot the difference to your configuration? :)

**Comment by bomb-on** [comment]
@dkellner Yes, I do query for `User` during the authentication. It is a simple query like

```
user = db.session.query(Users).filter(Users.key == userid).one()
```
and I also set the `auth_value` later on in same class/method:
```
self.set_request_auth_value(user.id)
```

 I got around this exception by adding modifying the `DOMAIN` dict:
```
DOMAIN['users'].update({'auth_field': None})
```
 and adding the hook where I am sorting out the `/users` endpoint in a specific way, e.g.:
```
def pre_request_get(resource, request, lookup):
    if resource == 'users' and some_other_condition == True:
        abort(403)
```

I don't use predefined filters at all.

**Comment by bomb-on** [comment]
I have noticed just now that tests for my own app are not passing... Actually not starting properly at all because I am getting the very well known Eve exception:
`eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.`

I'll try to figure it out and will report back what was the problem...

**Comment by dkellner** [comment]
In the meantime we've migrated our real world application to the `config` branch. We've found some minor issues and fixed them already.  The next step is to refactor & rebase this and merge in master.

**Comment by dkellner** [comment]
Merged after autosquash & rebase.

**Pull request merged**
