### PR TITLE
Fix #139: Use absolute imports instead of relative

### LINKED ISSUE #139: Tidy up examples directory
Running the examples as expected does not work:

```sh
git clone https://github.com/RedTurtle/eve-sqlalchemy.git
cd eve-sqlalchemy
virtualenv -p python3 .  # or python2, does not matter
source bin/activate
pip install .
cd examples
python trivial.py  # works, as it does not contain relative imports
python sqla_example.py  # fails with "cannot perform relative import"
```

Furthermore, I would like to organize the contents of the `examples/` directory, preferrably one well-named subdirectory for each example, containig a main.py (or app.py, or same name as the directory) to run and a proper module (maybe called `sample`) for the application code. This would also solve the import issue.

As a bonus, one could look at all the comments in there and improve them.

### PR DESCRIPTION
**Pull request by joystein**

### CODE REVIEW

**Comment by dkellner** [comment]
Thanks for your PR! Can you take a look at the failing tests?

And do you know if this works in every case / Python version? `examples/` has no `__init__.py`, so I'm not sure if you can import from the examples-module properly. The tests might not cover running the examples.

**Comment by joystein** [comment]
It was the isort test that was failing. Import order fixed in latest commit. The examples works well without `__init__.py` when running directly from command-line on py3, but i guess they will fail with py2. Running with tox seems to confirm this.

I can add an `__init__.py` file, but not sure if it makes sense to add tests for the examples?

**Comment by dkellner** [comment]
I'd love to see tests for the examples, too. But then I'd like to have some kind of doctests with sample requests that can both serve as documentation and integration test.

That said, we can focus on fixing the import issue in this PR and delay further improvements after releasing 0.5. Can you add an `__init__.py`, test with both Python 2 and 3 and merge your commits into one? Thank you!

**Comment by joystein** [comment]
Package file added for examples. Tested in both py2 and py3.

As for tests, i tried to do a simple import test:
```
import os

def test_import_trivial_example():
    if 'EVE_SETTINGS' in os.environ:
        del os.environ['EVE_SETTINGS']
    from examples import trivial
    assert trivial.app

def test_import_sqla_example():
    os.environ['EVE_SETTINGS'] = 'eve-sqlalchemy/examples/settings.py'
    from examples import sqla_example
    assert sqla_example.app
    del os.environ['EVE_SETTINGS']
```

These work fine if one of them is commented out, but with both enabled, there seems to be a issue with reuse of the in-memory database or something.

I have yet to see a solution akin to what you describe; running processes from inside doctests/sphinx-doc, checking the result and producing output for documentation. If you have any pointers or further ideas to explore, i would be interested to know.

**Comment by dkellner** [comment]
I'd like to keep this as a small change and just fix the import issue - partly because I'm not sure if/when a full-featured doctest-solution will land :).

I'm not yet happy with the changes, though. isort now rightly thinks `examples` is a third-party module and after reconsidering I think adding the `__init__.py` was a bad idea. We should take the proposed way in #139 and just move those two examples in a subdirectory each (maybe named 'trivial' and 'simple'). That's by the way Flask does that, too: https://github.com/pallets/flask/tree/master/examples .

**Comment by denis-trofimov** [comment]
Hi! I am new to eve-sqlalchemy.
Got this possible mindlessly quick patch. Don't know how to help here (myself).
[Should PR or not?](https://github.com/denis-trofimov/eve-sqlalchemy)

**Comment by dkellner** [comment]
@denis-trofimov Thanks for your will to contribute! This is quite close to what @joystein suggested at first, but unfortunately it's not working in both Python 2 and 3. I think for this issue it's best to wait for @joystein to respond to my latest comment here. If he says he doesn't have time to do it at the moment, he will be happy if you want to take over this issue!

**Comment by denis-trofimov** [comment]
@dkellner thank you for the clue. I should know eve, eve-sqlalchemy better to contribute something worthy accoding to your CoC, code quality.

**Comment by joystein** [comment]
@dkellner Sorry for the late reply.

My main motivation here is to help getting a new release out. I think that an issue with an example that fails, is a valid blocker for a release, while an issue that wants to improve the structure of the project, maybe not necessarily so?

As such i consider whats in this pull request a fix that should make #139 not block a release. At the same time i fully agree that the structure of the examples should be improved.

It might appear silly on my part to quibble about such a trivial change, but i guess we are all busy.. 

However, if something along the lines of what you mention in #139 is required for having this pull request accepted, i will go ahead and implement that as well.

**Comment by dkellner** [comment]
I understand your point and I was ready to go for an easy fix in the beginning. But introducing a new top-level module with a generic name like `examples` (even though we of course would not package it) feels wrong to me. And I'd estimate that moving this files in subfolders and maybe renaming them will not cost that much more time that it's worth to actually go with that compromise.

For the release: Yes, I want to get it out soo, too. But are breaking changes since 0.4.1 already and I'm about to introduce a few more regarding the way we configure `DOMAIN` to fix several issues (regarding the use of `id_field`, `item_lookup_field` etc. and not altering the SQLAlchemy models anymore while registering them for Eve). I'd prefer to have this changes out in one release, so users have a "painful" upgrade experience just once. And then maintain backwards compatibility again.

**Comment by joystein** [comment]
Sounds reasonable to me. I will see if i can find time during the coming week to implement your suggestion.

Also looking forward to the improvements you mention and eventually a release :-)

**Comment by dkellner** [comment]
Thanks a lot! :)

**Pull request closed without merging**
